# Generated by Django 4.1.7 on 2023-04-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_artist_songs_song_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
