# Generated by Django 4.1.7 on 2023-04-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='translated_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='translated_lyrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='song',
            name='translated_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
