# Generated by Django 4.1.7 on 2023-04-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
