# Generated by Django 4.1.7 on 2023-08-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_paragraph_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='translated_lyrics',
        ),
        migrations.RemoveField(
            model_name='song',
            name='translated_title',
        ),
    ]
