# Generated by Django 4.1.7 on 2023-08-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_remove_song_translated_lyrics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='song',
            name='translated_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
